### ISSUE TITLE
Version 2 task checklist

### ISSUE THREAD

**Issue by dcgauld** [leftlogic/leftlogic#1]
### General
- [x] Decide on appropriate orange colour (Remy may have a solution for this).
- [x] Decide on layout of page footer.
- [x] Decide what content should be added to the sidebar (newsletter sign up etc.)
### Homepage
- [ ] Decide where the 'clients' section should go (and what it should look like).
- [x] Edit 'View project' links to navigate to the actual projects (and maybe the preview images too).
- [x] Decide whether the large heading's text is okay.
- [x] Decide whether the rough edit of Remy's shelf image is okay.
### About
- [x] Add social media icons to each team member's profile (issue #4).
### Hiring
- [x] Should 'Headline of employment opportunity' be a job title?
### Training
- [x] Add a sub-page for each workshop.
- [x] Add a grid of nice images for each workshop on the 'training' page.
- [x] Improve blockquote styling.
### Contact
- [x] Implement contact form (server side).
- [x] Decide on some (if any) extra copy to go above the contact form.
- [x] Do we need extra validation on top of HTML5's 'email' etc.?
- [x] Do we need the `<select>` element for 'Where did you find us'? If so, what should be included in this list?
### Other
- [x] Move navigation object into global variable.
- [x] Carry on making responsive (look into two columned layout sections etc.)
- [x] Design the 404 page.
- [ ] Implement behind the scenes stuff for 404 page (later on).
- [x] Google Analytics?
- [ ] Visit Left Logic :+1:
- [x] Add 'about' page to hold information and images about the company
### Things I need from @remy:
- [x] Copy for Full Frontal text on homepage (currently same as JS Bin).
- [x] Copy for each member of the team.
- [x] If needed, a new picture for each member of the team (might look good in grayscale?).
- [x] Guidance soon on backend implementation for contact form and 404 capture.
- [x] Guidance on moving projects such as Entity Lookup into a new layout (if needed).
- [ ] A full check of all wording across the site (including button text etc).
- [x] Maybe more if I think of anything...
